config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def new
    @restaurant = Restaurant.new
  end

  def create
    Restaurant.create params[:restaurant].permit(:name, :description)
    redirect_to '/restaurants'
  end

  def index
    @restaurants = Restaurant.all
  end

  def edit
    @restaurant = Restaurant.find params[:id]
  end

  def update
    @restaurant = Restaurant.find params[:id]
    @restaurant.update params[:restaurant].permit(:name, :description)
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find params[:id]
    @restaurant.destroy
    redirect_to '/restaurants'
  end

  def show
    @restaurant = Restaurant.find params[:id]
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find params[:restaurant_id]
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find params[:restaurant_id]
    @restaurant.reviews << Review.create(params[:review].permit(:name, :content, :rating))
  
    redirect_to restaurant_path(@restaurant)
  end

  def edit
    @restaurant = Restaurant.find params[:restaurant_id]
    @review = Review.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find params[:restaurant_id]
    @review = Review.find params[:id]
    @review.update params[:review].permit(:name, :content, :rating)
    redirect_to @restaurant
  end

  def destroy
    @restaurant = Restaurant.find params[:restaurant_id]
    @review = Review.find params[:id]
    @review.destroy
    redirect_to @restaurant
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yelpclone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <br>
  <%= form.label :description %>
  <%= form.text_area :description %>

  <br>
  <%= form.submit %>
<%end%>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<% if @restaurants.none? %>
  No restaurants yet!
  <p> Would you like to <%= link_to 'create one?', new_restaurant_path %> </p>
<% end %>


<% @restaurants.each do |restaurant| %>
  <h1>
    <%= link_to restaurant.name, restaurant %>
  </h1>
  <h3> 
    Created <%= time_ago_in_words(restaurant.created_at) %> ago
  </h3>
  <p><%= truncate(restaurant.description, :length => 140) %></p>
  
  <%= link_to 'Edit restaurant', edit_restaurant_path(restaurant) %>
  
  <%= link_to 'Remove restaurant', restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' } %>
<%end%>

<h3><%= link_to 'Add a new restaurant', new_restaurant_path %></h3>

app/views/restaurants/new.html.erb
<%= form_for @restaurant do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <br>
  <%= form.label :description %>
  <%= form.text_field :description %>

  <br>
  <%= form.submit %>
<%end%>

app/views/restaurants/show.html.erb
<h1>Restaurant page for <%= @restaurant.name %></h1>
    <p><%= @restaurant.description %></p>
    <%= link_to 'Add a review', new_restaurant_review_path(@restaurant) %>
    <%= link_to 'View All', restaurants_path %> 
     <%= link_to 'Edit restaurant', edit_restaurant_path(@restaurant) %> 
    
    <%= link_to 'Remove restaurant', restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you sure?' } %> 
    <% @restaurant.reviews.each do |review| %>
      <p><%= review.content %> - <%= review.rating %></p>

      <h4><%= link_to 'Edit Review', edit_restaurant_review_path(review.restaurant_id, review.id) %> </h4>
      <h4><%= link_to 'Delete', restaurant_review_path(review.restaurant_id, review.id), method: :delete, data: { confirm: 'Are you sure you want to delete your review?'} %>

     <%end%>

app/views/reviews/_form.html.erb
<%= form_for [@restaurant, @review] do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <br>

  <%= form.label :content, 'Review' %>
  <%= form.text_area :content %>

  <%= form.label :rating %>
  <%= form.select :rating, options_for_select(1..5) %>

  <%= form.button 'Submit' %>
  
<%end%>

app/views/reviews/edit.html.erb
<%= render 'form' %>

app/views/reviews/new.html.erb
<%= render 'form' %>